language: generic

os:
  - linux
  - osx

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Lioness.xcworkspace
  - IOS_FRAMEWORK_SCHEME="Lioness iOS [Double]"
  - MACOS_FRAMEWORK_SCHEME="Lioness macOS Release [Double]"
  - EXAMPLE_SCHEME="macOS Example"

  matrix:
    - JOB=Linux
    - JOB=OSX_Xcode DESTINATION="OS=10.3.1,name=iPhone 7 Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="NO" BUILD_EXAMPLE="NO"  CODE_COV="NO"
    - JOB=OSX_Xcode DESTINATION="OS=9.0,name=iPhone 6"           SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="NO" BUILD_EXAMPLE="NO"  CODE_COV="NO"
    - JOB=OSX_Xcode DESTINATION="arch=x86_64"                    SCHEME="$MACOS_FRAMEWORK_SCHEME"   RUN_TESTS="YES" BUILD_EXAMPLE="NO"  CODE_COV="YES"


osx_image: xcode8.3
after_success:
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    - bash <(curl -s https://codecov.io/bash)
  fi


dist: trusty
sudo: required
before_install:
  - DIR="$(pwd)"
  - cd ..
  - export SWIFT_VERSION=swift-3.1.1-RELEASE
  - wget https://swift.org/builds/development/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz
  - tar xzf $SWIFT_VERSION-ubuntu14.04.tar.gz
  - export PATH="${PWD}/${SWIFT_VERSION}-ubuntu14.04/usr/bin:${PATH}"
  - cd "$DIR"


script: 

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then

    set -o pipefail;
    xcodebuild -version;
    xcodebuild -showsdks;

    if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

    if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

    if [ $BUILD_EXAMPLE == "YES" ]; then
      travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

    if [ $CODE_COV == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES -enableCodeCoverage YES test;
    fi

    fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    swift build;
    .build/Debug/MyUnitTests;
    fi

